# Generated by Django 6.0.2 on 2026-02-20 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientation_score', models.IntegerField(default=0)),
                ('memory_score', models.IntegerField(default=0)),
                ('executive_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('reaction_time', models.FloatField(default=0.0)),
                ('speech_rate', models.FloatField(default=0.0)),
                ('pause_duration', models.FloatField(default=0.0)),
                ('word_count', models.IntegerField(default=0)),
                ('recording_duration', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(choices=[('Low', 'Low Risk'), ('Moderate', 'Moderate Risk'), ('High', 'High Risk')], default='Low', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.patient')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'db_table': 'assessments',
                'ordering': ['-created_at'],
            },
        ),
    ]
