# Generated by Django 6.0.2 on 2026-02-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='ml_dementia_probability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='ml_normal_probability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='ml_prediction',
            field=models.CharField(choices=[('dementia', 'Dementia Detected'), ('normal', 'Normal'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
