# Generated by Django 5.0.1 on 2026-03-02 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('exercise', 'Exercise Schedule'), ('diet', 'Diet Chart'), ('task', 'Clinical Task')], default='exercise', max_length=20)),
                ('content', models.JSONField(default=dict)),
                ('special_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='core.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='core.patient')),
            ],
            options={
                'verbose_name': 'Clinical Plan',
                'verbose_name_plural': 'Clinical Plans',
                'db_table': 'clinical_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
