# Generated by Django 6.0.2 on 2026-03-03 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_clinicalplan_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOCAAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visuospatial_score', models.IntegerField(default=0)),
                ('naming_score', models.IntegerField(default=0)),
                ('memory_score', models.IntegerField(default=0)),
                ('attention1_score', models.IntegerField(default=0)),
                ('attention2_score', models.IntegerField(default=0)),
                ('attention3_score', models.IntegerField(default=0)),
                ('language_score', models.IntegerField(default=0)),
                ('abstraction_score', models.IntegerField(default=0)),
                ('orientation_score', models.IntegerField(default=0)),
                ('delayed_recall_score', models.IntegerField(default=0)),
                ('total_moca_score', models.IntegerField(default=0)),
                ('answers_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moca_assessments', to='core.patient')),
            ],
            options={
                'verbose_name': 'MOCA Assessment',
                'verbose_name_plural': 'MOCA Assessments',
                'db_table': 'moca_assessments',
                'ordering': ['-created_at'],
            },
        ),
    ]
