# Generated by Django 6.0.2 on 2026-03-03 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_patient_assigned_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='core.patient')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='core.clinicalplan')),
            ],
            options={
                'verbose_name': 'Task Completion',
                'verbose_name_plural': 'Task Completions',
                'db_table': 'task_completions',
                'ordering': ['-completed_at'],
            },
        ),
    ]
