# Generated by Django 5.2.11 on 2026-03-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_taskcompletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senior_id', models.IntegerField()),
                ('original_text', models.TextField()),
                ('english_text', models.TextField()),
                ('language', models.CharField(max_length=10)),
                ('mood_score', models.IntegerField(blank=True, null=True)),
                ('emotion', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Diary Entry',
                'verbose_name_plural': 'Diary Entries',
                'db_table': 'diary_entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
