# Generated by Django 5.2.12 on 2026-03-05 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_diaryentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoulConnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1_answer', models.TextField(blank=True, null=True)),
                ('q2_answer', models.TextField(blank=True, null=True)),
                ('q3_answer', models.TextField(blank=True, null=True)),
                ('q4_answer', models.TextField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soul_connections', to='core.patient')),
            ],
            options={
                'verbose_name': 'Soul Connect Entry',
                'verbose_name_plural': 'Soul Connect Entries',
                'db_table': 'soul_connect_entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
