# Generated by Django 5.2.12 on 2026-03-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_soulconnect'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='crisis_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='sentiment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
