# Generated by Django 5.2.12 on 2026-03-05 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_diaryentry_crisis_flag_diaryentry_sentiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='core.patient')),
            ],
            options={
                'verbose_name': 'Chat History',
                'verbose_name_plural': 'Chat Histories',
                'db_table': 'chat_history',
                'ordering': ['created_at'],
            },
        ),
    ]
