# Generated by Django 5.2.12 on 2026-03-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_chathistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentry',
            options={'ordering': ['-is_starred', '-created_at'], 'verbose_name': 'Diary Entry', 'verbose_name_plural': 'Diary Entries'},
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
