# Generated by Django 5.2.12 on 2026-03-07 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_diary_entry_starred'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('sleep_rating', models.IntegerField()),
                ('food_rating', models.IntegerField()),
                ('day_rating', models.IntegerField()),
                ('exercise', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to='core.patient')),
            ],
            options={
                'verbose_name': 'Daily Checkin',
                'verbose_name_plural': 'Daily Checkins',
                'db_table': 'daily_checkins',
                'unique_together': {('patient', 'date')},
            },
        ),
    ]
