# Generated by Django 5.2.12 on 2026-03-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_dailycheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='preferred_lang',
            field=models.CharField(choices=[('en', 'English'), ('ta', 'Tamil'), ('hi', 'Hindi')], default='en', max_length=5),
        ),
    ]
