# Generated by Django 5.2.12 on 2026-05-29 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_patient_preferred_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='emotion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='emotion_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmotionalSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('dominant_emotion', models.CharField(max_length=50)),
                ('avg_mood_score', models.FloatField()),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='low', max_length=10)),
                ('crisis_count', models.IntegerField(default=0)),
                ('trend', models.CharField(default='stable', max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotional_summaries', to='core.patient')),
            ],
            options={
                'verbose_name': 'Emotional Summary',
                'verbose_name_plural': 'Emotional Summaries',
                'db_table': 'emotional_summaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
