# Generated by Django 5.2.12 on 2026-06-07 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_chathistory_emotion_chathistory_emotion_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='personality_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('plus', 'Plus')], default='free', max_length=10),
        ),
        migrations.CreateModel(
            name='BhaviMemoryFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_facts', to='core.patient')),
            ],
            options={
                'verbose_name': 'Bhavi Memory Fact',
                'verbose_name_plural': 'Bhavi Memory Facts',
                'db_table': 'bhavi_memory_facts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_date', models.DateField()),
                ('first_use_at', models.DateTimeField(blank=True, null=True)),
                ('reset_at', models.DateTimeField(blank=True, null=True)),
                ('minutes_used', models.FloatField(default=0.0)),
                ('upgrade_msg_shown', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_quotas', to='core.patient')),
            ],
            options={
                'verbose_name': 'Voice Quota',
                'verbose_name_plural': 'Voice Quotas',
                'db_table': 'voice_quotas',
                'ordering': ['-quota_date'],
                'unique_together': {('patient', 'quota_date')},
            },
        ),
    ]
